---
  #host: liet ke cac host
- hosts: all
  #become sudo = true
  become: true
  
  #task: cac nhiem vu duoc dinh nghia trong playbook
  tasks:

  #xoa nginx
  - name: remove nginx package
    yum:
      name: nginx
      state: absent
    #state: absent chinh la remove
